<a href="https://colab.research.google.com/github/dp1706/Machine-Learning/blob/master/ML_assignment_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1. get the python version  

import sys
print("Python version :")
print (sys.version)
print()

Python version :
3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0]



In [ ]:
#2.  python program to locate python site-packages

import site; 
print(site.getsitepackages())
print()


['/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.6/dist-packages']



In [ ]:
#3. python program to get path and currently executing file name

print("path: ", sys.argv[0])
print("name of file: ", sys.argv[0].split('/')[-1])
print()

path:  /usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py
name of file:  ipykernel_launcher.py



In [ ]:

#4. python program to randomly generate two matrices and multiply them

import numpy as np

A= np.random.randint(1,10,size=(2,3))
print(A)
print()
B= np.random.randint(1,10,size=(3,2))
print(B)
print("result:")
print()
result = np.dot(A,B) 
  
for r in result: 
    print(r) 

[[9 6 9]
 [7 4 2]]

[[9 5]
 [7 7]
 [4 7]]
result:

[159 150]
[99 77]


In [ ]:

#5 for loop and average of the result metrices

import numpy as np
print()
average=[[0,0],[0,0]]

for i in range(5):
     A= np.random.randint(1,10,size=(2,3))
     B= np.random.randint(1,10,size=(3,2))

     result = np.dot(A,B)
     print("matrix",i,":") 
     print(result)
     print()
     average=average+result

average=average/5
print("avergae is: ")
print(average)     



matrix 0 :
[[ 95  28]
 [109  33]]

matrix 1 :
[[109 120]
 [ 99 117]]

matrix 2 :
[[125 137]
 [ 66  82]]

matrix 3 :
[[31 58]
 [23 62]]

matrix 4 :
[[86 38]
 [99 60]]

avergae is: 
[[89.2 76.2]
 [79.2 70.8]]


In [ ]:

#6  reading and writing in a csv file using python
import csv
csvfile = open('matrix.csv','w', newline='')
obj = csv.writer(csvfile)
obj.writerows(average)
csvfile.close()

csvfile1=open('matrix.csv','r', newline='')
data = list(csv.reader(csvfile1))
print()
print(data) 
print()
t_matrix = zip(*data) 
for row in t_matrix:
   print(row)


[['89.2', '76.2'], ['79.2', '70.8']]

('89.2', '79.2')
('76.2', '70.8')


In [ ]:
#7   python program to find mean , mode and median of a matrix

#import numpy as np
from scipy import stats

mean = np.mean(average)

median = np.median(average)

mode = stats.mode(average)

print('Mean is ', mean)

print('Median is ', median)

print('Mode is ', mode[0])

Mean is  78.85000000000001
Median is  77.7
Mode is  [[79.2 70.8]]


In [ ]:

#8 upper triangular matrix 

print("\nupper triangular matrix: \n ", np.triu(average,0))


upper triangular matrix: 
  [[89.2 76.2]
 [ 0.  70.8]]
